// <auto-generated/>
using System.Runtime.CompilerServices;

// ReSharper disable once CheckNamespace
namespace Cake.Gitter
{
    /// <summary>
    /// This namespace contains Gitter aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}

// ReSharper disable once CheckNamespace
namespace Cake.Gitter.Chat
{
    /// <summary>
    /// This namespace contain types for the Gitter Chat tool.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}